#!/bin/bash

# Copy (via ssh) to each host specified on the command line
# or substitute the $@ for a list of your hosts you you don't have to type them in
# you will need to setup your ssh config so you can connect 
# by simply entering 'ssh hostname'. Google it if you don't 
# know what I am talking about

for HOST in $@  ; do
  echo "copying to $HOST"
  #scp ./backuppc-lvsnap-wrapper $HOST:/usr/local/bin/backuppc-lvsnap-wrapper
done
